services:
  database:
    image: postgres:18-alpine
    container_name: librearchive_db
    restart: always
    environment:
      POSTGRES_USER: libreuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: librearchive
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - librearchive_net

networks:
  librearchive_net:
    driver: bridge
